import AboutContents from "@/components/AboutContents";
import React from "react";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <div>
      <AboutContents />
    </div>
  );
};

export default About;
