import AboutContents from "@/components/AboutContents";
import { Headland_One } from "next/font/google";
import React from "react";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const headLand = Headland_One({
  weight: ["400"],
  subsets: ["latin"],
});

const About = () => {
  return (
    <div>
      <AboutContents />
      <p className={` ${headLand.className}`}>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Inventore
        dignissimos quibusdam dolor eaque consequatur nobis amet magni qui
        doloremque, quia ipsam hic, expedita facilis! Culpa eos, necessitatibus
        facere totam molestiae tempora. Modi deleniti repellat minima labore
        accusamus cum, delectus aut expedita, fugit, iure sequi soluta. Ipsam
        excepturi temporibus a cum corrupti veniam, ducimus necessitatibus
        suscipit ut in quidem cumque. Quod in qui quasi quae dolores
        exercitationem odio voluptatum perferendis dolorum delectus est ut
        repellat error, eaque autem! Excepturi quia inventore nobis ipsam minima
        eaque nam cum voluptatum nesciunt sunt eos delectus ea ducimus repellat
        placeat laborum voluptate asperiores mollitia, et tempora a porro.
        Perferendis impedit, vero modi sapiente consequatur facere similique
        voluptates assumenda. Atque nemo dolor sint facere maiores voluptatem
        eligendi quaerat officiis porro, aspernatur consequatur et laborum
        necessitatibus beatae. Expedita nulla cumque unde necessitatibus eaque
        nam ut hic suscipit ratione sed nemo perferendis ipsa praesentium error
        consectetur veritatis, eum vero id est obcaecati recusandae! Dolore
        consequuntur odit sapiente ea non aperiam iste consequatur asperiores
        nostrum deserunt totam quas aliquam blanditiis, sed temporibus eveniet
        soluta doloribus quidem repudiandae sequi ipsa mollitia velit eum
        facere. Doloribus voluptatum temporibus non impedit, modi, hic officiis
        cumque nulla, aspernatur iste labore. Ipsa cupiditate dolor mollitia
        molestiae dolorem est eum voluptate alias molestias fugiat, ea quaerat
        accusantium! Quisquam, quidem! Esse sint recusandae excepturi, maiores
        deleniti quasi omnis at autem qui magnam? Blanditiis totam cum dolores
        iusto architecto voluptas expedita, delectus incidunt modi omnis!
        Suscipit fugit saepe vel illo in quas necessitatibus odio architecto?
        Repudiandae architecto suscipit rerum neque dolor dignissimos sapiente!
        Id facilis earum aliquam sit repellat doloremque consectetur nesciunt
        tenetur numquam totam deserunt veniam harum quia cum provident
        laudantium illum hic, veritatis cumque reiciendis? Optio facere
        consectetur, suscipit, ex beatae eveniet veritatis, nostrum enim aperiam
        odit modi nulla laborum rerum accusantium corporis aliquid architecto ea
        eum dicta? Rerum impedit cupiditate quas! Deleniti facilis rerum
        reiciendis modi expedita. Quod architecto asperiores voluptatibus ea
        repellendus nulla laborum nemo quis ducimus animi reiciendis inventore
        assumenda error tenetur quam dolor eum, iure natus eos corrupti! Rem
        voluptates reprehenderit officia amet! Blanditiis iure dicta id cumque
        odio sint adipisci inventore voluptas tempore? Quaerat, repellat.
        Impedit perferendis placeat illo perspiciatis fugit! Odio perferendis
        voluptatum harum libero aliquid perspiciatis, veniam praesentium autem
        provident placeat, cupiditate in accusamus deserunt quos iure voluptate
        dolorum voluptas impedit deleniti repudiandae sed ut. Ea accusantium
        deleniti doloribus delectus distinctio, neque architecto aperiam.
        Voluptatibus, aliquam commodi? Id nisi voluptatibus, eveniet dolores
        amet reprehenderit ex perferendis porro sit aliquam, animi cupiditate
        dicta sint esse officiis ullam doloribus? Nisi dignissimos veritatis
        consequatur, aut soluta animi perferendis, unde labore quia quibusdam
        eveniet! Perspiciatis voluptates autem nam laborum assumenda tempore
        dignissimos quae, qui fugit iste. Quaerat eaque soluta qui, sit
        molestiae minus accusamus exercitationem maiores laboriosam veniam
        quidem esse maxime vel, fugit quo in provident autem delectus
        praesentium eius hic porro quibusdam unde. Facilis cupiditate tempore
        nam. Iste, vitae libero sapiente quia animi voluptates sunt! Ea iure
        soluta illum commodi doloremque consequuntur, aperiam ab nulla sapiente
        beatae voluptatem nostrum at ut quisquam corporis itaque. Rerum, dolores
        consequatur, temporibus porro repellat officiis, aperiam sit qui esse
        earum fugiat. Dicta distinctio itaque, vero quasi ea autem nesciunt
        iusto delectus totam rem reprehenderit asperiores? Odio ipsum explicabo
        porro consequuntur excepturi magni non numquam sed officiis ratione!
        Veniam labore deleniti tempore exercitationem accusantium beatae esse
        ipsum amet expedita, maiores ducimus accusamus, architecto, eligendi
        illo praesentium dolores? Quo incidunt provident voluptatem ipsa,
        praesentium quam reiciendis delectus architecto! Architecto numquam quae
        maiores repudiandae, aspernatur officia incidunt amet odio hic vero,
        quidem recusandae dignissimos commodi voluptatibus libero corrupti.
        Dicta reiciendis, officiis quisquam repellendus, voluptates dolorem
        molestias ipsa perspiciatis laborum facere necessitatibus consequatur
        sint aut exercitationem nihil sunt a. Porro, aliquid aliquam quaerat
        accusamus ratione reprehenderit sit minus labore eius blanditiis
        sapiente voluptatum est fuga dolorum doloribus amet voluptates aperiam
        sequi dicta commodi dolorem, autem dolores esse. Quia, impedit maiores
        ab facere, nam mollitia id recusandae assumenda amet quae quibusdam
        nulla atque? Maiores esse, iure eos exercitationem modi libero fugit
        vero dolor dolores, non labore iste nam. Doloremque, neque nobis?
        Perspiciatis iusto facere ipsam quod dolor culpa, officia quisquam
        incidunt reiciendis, adipisci excepturi ipsum est iure quasi iste!
        Iusto, dolorum ratione incidunt molestiae explicabo aliquam deserunt
        dolore aspernatur ipsum dicta sapiente voluptatibus, aperiam molestias
        vitae quam. Vero culpa similique eaque, magni ab quae, repellendus,
        inventore aspernatur vitae soluta consequuntur nobis. Architecto ut
        ipsa, illum enim, pariatur, laudantium omnis perspiciatis tenetur magnam
        id consectetur quae totam dignissimos dolores cum ratione officiis
        maiores itaque! Delectus earum saepe deserunt, nesciunt ratione
        blanditiis praesentium optio eligendi odio reprehenderit voluptas
        voluptate possimus deleniti, enim non amet explicabo eos dolorem ea id.
        Voluptate vel esse, fuga eligendi perferendis natus ipsa iste?
        Consequatur laboriosam provident eius! Illo nisi accusantium
        consequuntur sit eos! Quas, tempora. Aut debitis provident
        exercitationem maxime explicabo sunt dignissimos laborum. Necessitatibus
        delectus voluptas dolorem cupiditate quam unde ratione eos sunt
        blanditiis nostrum dolorum repudiandae consectetur, laborum earum
        asperiores, quod excepturi, veniam error ad reprehenderit voluptatum
        perferendis quisquam suscipit! Ullam praesentium tenetur assumenda eius
        corrupti repellendus animi debitis quibusdam perferendis doloribus
        laboriosam soluta labore architecto fuga blanditiis ad mollitia nam
        magnam, in cum sit ipsam. Quidem amet asperiores officia nisi, magni
        pariatur! Distinctio autem velit obcaecati illum ratione, qui eum quo
        magni officia quis voluptate quaerat doloremque ad beatae. At cumque
        dolor et id quo iure deserunt enim, nostrum autem quam! Eius
        reprehenderit libero rerum obcaecati suscipit atque natus explicabo
        quaerat, debitis, quam voluptatem fugiat veniam asperiores sequi numquam
        dolorem minus repellat quidem voluptates nemo omnis sit molestias! In
        quae, illum ab laboriosam quos molestias quaerat quasi. Maxime autem
        cumque mollitia harum doloremque, laboriosam odit non asperiores dolorum
        provident perferendis ad veniam sit vitae et, ullam porro repellendus
        velit iure. Atque placeat, culpa itaque blanditiis cupiditate at? Fugit
        enim est rerum dolor, deleniti magni cumque molestiae unde a debitis ad
        vel dolorem molestias, amet aut. Dolore enim eveniet, voluptatem iure
        pariatur, earum voluptas eum fugit inventore laboriosam dolor? Voluptas
        soluta, ea at, ducimus natus quas magnam consequuntur expedita deleniti,
        nulla accusamus provident. Aspernatur, rem?
      </p>
    </div>
  );
};

export default About;
