import BlogBox from "@/components/BlogBox";
import { getPost } from "@/components/jsFunction/blogApi";
import Link from "next/link";
import React from "react";

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

const Blogs = async () => {
  const posts = await getPost();

  return (
    <div>
      <h1 className="text-center font-bold text-xl my-10">Blogs Page</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {posts.map((post, idx) => (
          <div key={idx}>
            <BlogBox post={post} />
          </div>
        ))}
      </div>
    </div>
  );
};

export default Blogs;
