import { singleBlog } from "@/components/jsFunction/singleBlogApi";
import React from "react";

export const generateMetadata = async ({ params }) => {
  const post = await singleBlog(params?.id);
  return {
    title: `${post?.title}`,
    description: "Generated by create next app",
  };
};
// export const metadata = {
//   title: "Blog",
//   description: "Generated by create next app",
// };

const SingleBlog = async ({ params }) => {
  const post = await singleBlog(params?.id);
  // console.log("Post: ", post);

  const { id, userId, title, body } = post;

  // const findBlog = students.find((student) => student.id == id);

  return (
    <div className="w-1/2 p-4 border rounded-xl mx-auto my-4">
      <div className="flex justify-between my-4 text-white">
        <h1>id: {id} </h1>
        <h1>User id: {userId}</h1>
      </div>
      <h1 className="text-white font-bold"> {title}</h1>
      <div className="border rounded-md p-2 my-2">
        <h1 className="text-white "> {body}</h1>
      </div>
    </div>
  );
};

export default SingleBlog;
